// AUTO-GENERATED by C:\ROK\_ui-tools\gen-mge-commanders.py — do not hand-edit rows.
// Every LEGENDARY commander in the live game (rokbattles game-data table,
// July 2026), grouped for the MGE event picker. Newest first (release order).
// Types: first specialty from the commander reference, with web-verified
// overrides for the newest commanders (riseofkingdomsguides.com). 'Other' =
// Engineering/Integration (rarely MGE-featured, kept findable).

export type MgeCommanderType = 'Infantry' | 'Cavalry' | 'Archer' | 'Leadership' | 'Other';

export interface MgeCommander {
  name: string;
  type: MgeCommanderType;
  prime: boolean; // Prime version (MGE-featured upgrades of older legendaries)
}

export const MGE_COMMANDER_TYPES: MgeCommanderType[] = ['Infantry', 'Cavalry', 'Archer', 'Leadership', 'Other'];

/** Troop classes an MGE event can be themed on (matches the in-game format —
 * an "Infantry MGE" etc. — players then pick their commander of that class). */
export const MGE_EVENT_TYPES = ['Infantry', 'Cavalry', 'Archer', 'Leadership'] as const;
export type MgeEventType = (typeof MGE_EVENT_TYPES)[number];

/** If an event's focused_commander is a troop-class theme ("Infantry MGE" or
 * just "Cavalry"), return that type; null means a legacy single-commander
 * event (e.g. "Ivar") which keeps the old fixed-commander behavior. */
export function parseMgeEventType(focused: string): MgeEventType | null {
  const m = focused.trim().match(/^(Infantry|Cavalry|Archer|Leadership)(\s+MGE)?$/i);
  if (!m) return null;
  const t = m[1].toLowerCase();
  return (t.charAt(0).toUpperCase() + t.slice(1)) as MgeEventType;
}

/** Commanders players can apply with for a typed event, newest first. */
export function commandersForEventType(type: MgeEventType): MgeCommander[] {
  return MGE_COMMANDERS.filter((c) => c.type === type);
}

export const MGE_COMMANDERS: MgeCommander[] = [
  { name: 'Yahya ibn Khalid', type: 'Other', prime: false },
  { name: 'Pelagius', type: 'Cavalry', prime: false },
  { name: 'Elizabeth I', type: 'Other', prime: false },
  { name: 'Vercingetorix', type: 'Leadership', prime: false },
  { name: 'Hayam Wuruk', type: 'Archer', prime: false },
  { name: 'Alp Arslan', type: 'Archer', prime: false },
  { name: 'Ivar', type: 'Infantry', prime: false },
  { name: 'Sun Tzu', type: 'Infantry', prime: true },
  { name: 'Gang Gamchan', type: 'Cavalry', prime: false },
  { name: 'David IV', type: 'Cavalry', prime: false },
  { name: 'Hector', type: 'Leadership', prime: false },
  { name: 'Achilles', type: 'Cavalry', prime: false },
  { name: 'Pepin III', type: 'Other', prime: false },
  { name: 'Casimir III', type: 'Leadership', prime: false },
  { name: 'Mary I', type: 'Other', prime: false },
  { name: 'Archimedes', type: 'Other', prime: false },
  { name: 'Afonso de Albuquerque', type: 'Other', prime: false },
  { name: 'Bai Qi', type: 'Infantry', prime: false },
  { name: 'Arthur Pendragon', type: 'Cavalry', prime: false },
  { name: 'Subutai', type: 'Cavalry', prime: false },
  { name: 'Matthias I', type: 'Leadership', prime: false },
  { name: 'Qin Shi Huang', type: 'Archer', prime: false },
  { name: 'Shapur I', type: 'Archer', prime: false },
  { name: 'Tokugawa Ieyasu', type: 'Infantry', prime: false },
  { name: 'Siyaj K\'ak\'', type: 'Archer', prime: false },
  { name: 'John Hunyadi', type: 'Leadership', prime: false },
  { name: 'Stephen III', type: 'Leadership', prime: false },
  { name: 'Philip II', type: 'Cavalry', prime: false },
  { name: 'Ragnar Lodbrok', type: 'Infantry', prime: true },
  { name: 'Scipio Aemilianus', type: 'Infantry', prime: false },
  { name: 'Choe Yeong', type: 'Archer', prime: false },
  { name: 'Shajar al-Durr', type: 'Archer', prime: false },
  { name: 'William Wallace', type: 'Infantry', prime: false },
  { name: 'Belisarius', type: 'Cavalry', prime: true },
  { name: 'Eleanor of Aquitaine', type: 'Leadership', prime: false },
  { name: 'Gajah Mada', type: 'Leadership', prime: false },
  { name: 'Gonzalo de Córdoba', type: 'Other', prime: false },
  { name: 'Lapulapu', type: 'Leadership', prime: false },
  { name: 'Hermann', type: 'Archer', prime: true },
  { name: 'Ashurbanipal', type: 'Archer', prime: false },
  { name: 'Liu Che', type: 'Infantry', prime: false },
  { name: 'Gorgo', type: 'Infantry', prime: false },
  { name: 'Justinian I', type: 'Cavalry', prime: false },
  { name: 'Huo Qubing', type: 'Cavalry', prime: false },
  { name: 'Pyrrhus', type: 'Infantry', prime: false },
  { name: 'Zhuge Liang', type: 'Archer', prime: false },
  { name: 'Dido', type: 'Archer', prime: false },
  { name: 'Heraclius', type: 'Leadership', prime: false },
  { name: 'Babur', type: 'Cavalry', prime: false },
  { name: 'Margaret I', type: 'Leadership', prime: false },
  { name: 'Sargon the Great', type: 'Infantry', prime: false },
  { name: 'Tariq ibn Ziyad', type: 'Cavalry', prime: false },
  { name: 'Joan of Arc', type: 'Other', prime: true },
  { name: 'Jan Žižka', type: 'Cavalry', prime: false },
  { name: 'Boudica', type: 'Other', prime: true },
  { name: 'Henry V', type: 'Archer', prime: false },
  { name: 'Thutmose III', type: 'Archer', prime: false },
  { name: 'Scipio Africanus', type: 'Leadership', prime: true },
  { name: 'Flavius Aetius', type: 'Infantry', prime: false },
  { name: 'Alexander Nevsky', type: 'Cavalry', prime: false },
  { name: 'Bertrand du Guesclin', type: 'Cavalry', prime: false },
  { name: 'Suleiman I', type: 'Leadership', prime: false },
  { name: 'Honda Tadakatsu', type: 'Infantry', prime: false },
  { name: 'Amanitore', type: 'Archer', prime: false },
  { name: 'Gilgamesh', type: 'Infantry', prime: false },
  { name: 'Kʼinich Janaabʼ Pakal', type: 'Leadership', prime: false },
  { name: 'Cheok Jun-gyeong', type: 'Infantry', prime: false },
  { name: 'Ragnar Lodbrok', type: 'Infantry', prime: false },
  { name: 'Xiang Yu', type: 'Infantry', prime: false },
  { name: 'Jadwiga', type: 'Cavalry', prime: false },
  { name: 'Trajan', type: 'Infantry', prime: false },
  { name: 'Moctezuma I', type: 'Other', prime: false },
  { name: 'Nebuchadnezzar II', type: 'Infantry', prime: false },
  { name: 'Cyrus the Great', type: 'Leadership', prime: false },
  { name: 'Lu Bu', type: 'Leadership', prime: false },
  { name: 'Zenobia', type: 'Infantry', prime: false },
  { name: 'Harald Sigurdsson', type: 'Infantry', prime: false },
  { name: 'William I', type: 'Leadership', prime: false },
  { name: 'Chandragupta Maurya', type: 'Cavalry', prime: false },
  { name: 'Yi Sun-sin', type: 'Archer', prime: false },
  { name: 'Artemisia I', type: 'Archer', prime: false },
  { name: 'Ramesses II', type: 'Archer', prime: false },
  { name: 'Leonidas I', type: 'Infantry', prime: false },
  { name: 'Guan Yu', type: 'Infantry', prime: false },
  { name: 'Theodora', type: 'Leadership', prime: false },
  { name: 'Ishida Mitsunari', type: 'Leadership', prime: false },
  { name: 'Takeda Shingen', type: 'Cavalry', prime: false },
  { name: 'Attila', type: 'Cavalry', prime: false },
  { name: 'Seondeok', type: 'Leadership', prime: false },
  { name: 'Edward of Woodstock', type: 'Archer', prime: false },
  { name: 'Tomyris', type: 'Archer', prime: false },
  { name: 'Æthelflæd', type: 'Leadership', prime: false },
  { name: 'Alexander the Great', type: 'Infantry', prime: false },
  { name: 'Charlemagne', type: 'Leadership', prime: false },
  { name: 'Genghis Khan', type: 'Cavalry', prime: false },
  { name: 'Wu Zetian', type: 'Leadership', prime: false },
  { name: 'Mulan', type: 'Other', prime: false },
  { name: 'Mehmed II', type: 'Leadership', prime: false },
  { name: 'Saladin', type: 'Cavalry', prime: false },
  { name: 'Cleopatra VII', type: 'Other', prime: false },
  { name: 'Hannibal Barca', type: 'Leadership', prime: false },
  { name: 'El Cid', type: 'Archer', prime: false },
  { name: 'Charles Martel', type: 'Infantry', prime: false },
  { name: 'Minamoto no Yoshitsune', type: 'Cavalry', prime: false },
  { name: 'Richard I', type: 'Infantry', prime: false },
  { name: 'Cao Cao', type: 'Cavalry', prime: false },
  { name: 'Yi Seong-Gye', type: 'Archer', prime: false },
  { name: 'Constantine I', type: 'Infantry', prime: false },
  { name: 'Frederick I', type: 'Leadership', prime: false },
  { name: 'Julius Caesar', type: 'Leadership', prime: false },
];
